# GET https://127.0.0.1:3443/users


POST https://127.0.0.1:3443/users
Content-Type: application/json

{
    "login": "Иванел",
    "email": "ivanel42@gmail.com",
    "password": "098753621",
    "roleId": 2
}