PATCH https://127.0.0.1:3443/messages/read/1
# Content-Type: application/json


# GET https://127.0.0.1:3443/messages/get?userId=1&chatPartnerId=2&adId=10

# POST https://127.0.0.1:3443/messages/send
# Content-Type: application/json

# {
#   "senderId": 2,
#   "recipientId": 2,
#   "adId": 10,
#   "content": "Привіт! Я зацікавлений у вашому оголошенні."
# }

# GET https://127.0.0.1:3443/ads

# POST https://127.0.0.1:3443/users/login
# Content-Type: application/json

# {
#     "login": "Насавпавтя",
#     "password": "098753621"
# }


# POST https://127.0.0.1:3443/ads/search?category=Электроника&minPrice=15000&maxPrice=20300

# GET  https://127.0.0.1:3443/role/2

# POST https://127.0.0.1:3443/users
# Content-Type: application/json

# {
#     "login": "Настя",
#     "email": "nastia23@gmail.com",
#     "password": "098753621",
#     "roleId": 2
# }

# DELETE  https://127.0.0.1:3443/ads/delete/3

# PUT https://127.0.0.1:3443/ads/update/4
# Content-Type: application/json

# {
#     "id": 4,
#     "title": "Продается кампуктер",
#     "description": "Kампуктер в отличном состоянии, полный комплект.",
#     "category": "Электроника",
#     "price": 20100,
#     "photos": [
#       "photo1",
#       "photo12"
#     ]
# }

# GET https://127.0.0.1:3443/ads
# POST https://127.0.0.1:3443/ads
# Content-Type: application/json

# {
#     "title": "Продается кампуктер",
#     "description": "Смартфон в отличном состоянии, полный комплект.",
#     "category": "Электроника",
#     "price": 20000,
#     "photos": [
#         "url_фото_смартфона_1",
#         "url_фото_смартфона_2"
#     ]
# }

# DELETE https://127.0.0.1:3443/users/delete/2

# PUT  https://127.0.0.1:3443/users/update/1
# Content-Type: application/json

# {
#     "login": "НовыйЛогин",
#     "email": "новый_email@gmail.com",
#     "password": "новый_пароль",
#     "roleId": 2
# }
